// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ESunBankTest.Models.SystemDB;

public partial class GovData13223
{
    public DateOnly Date { get; set; }

    public decimal TransToFinancial { get; set; }

    public decimal StocksAndBenefit { get; set; }

    public decimal Futures { get; set; }

    public decimal Bonds { get; set; }

    public decimal Securitized { get; set; }

    public decimal ShortTerm { get; set; }

    public decimal ForeignInvestment { get; set; }

    public decimal EntrustedDomestic { get; set; }

    public decimal EntrustedOverseas { get; set; }

    public decimal RealEstate { get; set; }

    public decimal GovLoansEconomic { get; set; }

    public decimal GovLoansAgriculture { get; set; }

    public decimal InsuredLoans { get; set; }
}