// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ESunBankTest.Models.SystemDB;

public partial class SystemDBEntities : DbContext
{
    public SystemDBEntities(DbContextOptions<SystemDBEntities> options)
        : base(options)
    {
    }

    public virtual DbSet<GovData13223> GovData13223 { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<GovData13223>(entity =>
        {
            entity.HasKey(e => e.Date);

            entity.Property(e => e.Bonds).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.EntrustedDomestic).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.EntrustedOverseas).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.ForeignInvestment).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Futures).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.GovLoansAgriculture).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.GovLoansEconomic).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.InsuredLoans).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.RealEstate).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Securitized).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.ShortTerm).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.StocksAndBenefit).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.TransToFinancial).HasColumnType("decimal(18, 0)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}